services:
  nginx:
    image: nginx:alpine
    ports:
      - "8081:80"  # Change 8080 to 8081 or any other available port
    volumes:
      - ./frontend-php:/var/www/html
      - ./frontend-php/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - my-network
    depends_on:
      - php

  php:
    build:
      context: ./frontend-php
      dockerfile: Dockerfile
    volumes:
      - ./frontend-php:/var/www/html
      - php_sessions:/tmp/sessions
    networks:
      - my-network
    environment:
      - PHP_SESSION_SAVE_HANDLER=files
      - PHP_SESSION_SAVE_PATH=/tmp/sessions
      - DB_HOST=db
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=app_stock
      - SESSION_SAVE_PATH=/tmp
    depends_on:
      db:
        condition: service_healthy

  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    volumes:
      - db_data:/var/lib/mysql
      - mysql_config:/etc/mysql/conf.d
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: app_stock
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      TZ: UTC
    command: 
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --explicit_defaults_for_timestamp=1
    ports:
      - "3306:3306"
    networks:
      - my-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "user", "-ppassword"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s

networks:
  my-network:
    driver: bridge

volumes:
  db_data:
  mysql_config:
  php_sessions: